- type: gameMapPool
  id: DefaultMapPool
  maps:
# DeltaV
  - Arena
#  - Academy - A new delta-v map that will possibly bring into rotation at a later point with some play tests
  - Asterisk
#  - Byoin - A new delta-v map that will possibly bring into rotation at a later point with some play tests
#  - Chibi - A new delta-v map that will possibly bring into rotation at a later point with some play tests
#  - Division - A new delta-v map that will possibly bring into rotation at a later point with some play tests
  - Edge
#  - Elegance - A new delta-v map that will possibly bring into rotation at a later point with some play tests
  - Glacier # - Maintainer WhiteLightningTwister
#  - Hammurabi - undergoing extensive maintenance (delta-v)
  - Lighthouse # Floof - Maintainer Dunrab
#  - Micro - to be revisited later ~Colin
  - Pebble
  - Shoukou
  - Submarine # Floof - Maintainer Dunrab
#  - Terra - A new delta-v map that will possibly bring into rotation at a later point with some play tests
  - TheHive
  - Tortuga
# Floofstation
  - Core # Floof - Maintainer Dunrab
  - Rad # Floof
  - Meta # Floof - Maintainer Dunrab
  - Kettle # Floof - Maintainer Dunrab
  - Fland # Floof - Maintainer Dunrab
  - Train # Floof - Maintainer Dunrab
  - Amber # Floof
  - Getaway # Floof - Maintainer Dunrab
